---
title: "Walkability Vizs"
author: "Gretchen Streett"
date: "11/3/2020"
output: html_document
---

```{r setup, }
library(leaflet)
library(rgdal)
library(tidyverse)
library(dplyr)
library(RColorBrewer)
library(stringr)
library(ggplot2)
library(plotly)

# All data is in this folder
mwalk <- readOGR(dsn = "mwalk.shp")
statefips <- read.csv("State FIPS.csv")
combined <- read.csv("combined.csv")
walkmi <- read.csv("walkmi.csv")
```

```{r Walkability Map: Michigan}
# Walkability map (Michigan Specific) 
## Target End state: blue water, better names, search by zip code/location, round Walkability Index Score, add points/layers for parks/schools/nature
walkmap <- leaflet(mwalk) %>%
 setView(lat = 44.2444, lng = -86.3243, zoom = 6) %>%
 addProviderTiles(providers$Stamen.TonerLite) %>%
  #add bloc borders
 addPolygons(stroke = TRUE, smoothFactor = 0.5,
  weight=1, color='#333333', opacity=1, 
  #chloropleth shading
  fillColor = ~colorQuantile("Greens", NatWalkInd)(NatWalkInd), 
  fillOpacity = 1, 
  #add pinpoint label
  label = ~stringr::str_c(CBSA_Name, ' ',
          formatC(NatWalkInd, big.mark = ',', format='f')),
  labelOptions = labelOptions(direction = 'auto'),
  #add hover highlight
  highlightOptions = highlightOptions(
          color='#000000', weight = 3,
          bringToFront = TRUE, sendToBack = TRUE))

walkmap2 <- walkmap %>% 
  addMiniMap() %>%
  addLegend(
  "bottomleft", 
  pal = colorQuantile("Greens", mwalk$NatWalkInd, n=5),
  values = ~NatWalkInd,
  title = htmltools::HTML("Walkability Index"),
opacity = 1, 
  labFormat = function(type, cuts, p) {
n = length(cuts)
paste0(cuts[-n], " – ", cuts[-1])}
)

walkmap3 <- walkmap2 %>%
    addEasyButton(easyButton(
    icon="fa-globe", 
    title="Zoom to Entire US Map",
    onClick=JS("function(btn, map){ map.setZoom(2.5); }"))) 
walkmap3
```

```{r Walkability Comparison: Manistee to State}
# Next steps: re-define "comparable rural areas"
myplot <- ggplot(data = combined, aes(x=`Location`, y=`Walkability`, fill=`Location`)) + 
  geom_bar(stat="identity", width=0.5) +
  scale_fill_brewer(palette="Dark2") +
  scale_x_discrete(limits=c("Manistee County", "Comparable Rural Area", "Entire State")) +
  geom_text(aes(label= round(`Walkability`, 2)), vjust=1.5, color="white", size=4)+
  labs(title="Walkability by Location")+
  theme_minimal() + 
  theme(legend.position="none")
myplot
```

```{r Walkability Comparison: All Michigan Counties}
# Next steps: Make font more readable, fix gap between bars and label on y axis

#Reorder Walkability in table to make chart pretty
walkmi <- transform(walkmi, `County` = reorder(`County`, -Walkability))
#plot it 
 plotc <- ggplot(walkmi, aes(x=County, y=Walkability)) + 
  geom_bar(stat="identity", width=.8, fill="tomato3") + 
  coord_flip() +
  labs(title="Walkability by County",
       caption="source: EPA") + 
  theme(axis.text.y=element_text(size= 5))
ggplotly(plotc)
```


