---
title: "COVID-19 Data Visualizations"
author: "Louisa Ong"
output:
  html_document:
    df_print: paged
---



```{r}

library(dplyr)
library(readr)
library(leaflet)
library(ggplot2)
library(coronavirus) # https://cran.r-project.org/web/packages/coronavirus/coronavirus.pdf
library(devtools)
library(htmlwidgets)
library(webshot)

# update_dataset()
covid_refresh <- refresh_coronavirus_jhu()
```


```{r}
View(covid_refresh)

summary_df <- covid_refresh %>% 
  filter(data_type == "cases_new") %>%
  filter(location_type == "country") %>%
  group_by(location_type, lat, long) %>%
  summarize(total_cases = sum(value)) %>% 
  rename(country = location_type) %>%
  arrange(-total_cases)

covid <- data.frame(summary_df)

names(covid)

covid_all <- coronavirus
covid_all$date <- as.Date(covid_all$date)

View(summary_df)

```

```{r}
# -------------- WORLD BUBBLE MAP SUM OF CONFIRMED CASES ------------------ # 

map_covid_cases <- leaflet(covid) %>% 
  addTiles() %>% 
  addCircles(lng = ~long, lat = ~lat,
             color = "#8f1d3f",
             radius = ~(covid$total_cases)/3,
             stroke = FALSE, 
             opacity = 0.9) %>% 
  addProviderTiles(providers$CartoDB.Positron)

map_covid_cases
```


```{r}
## save html to png
saveWidget(map_covid_cases, "map_covid_cases.html", selfcontained = FALSE)
webshot("map_covid_cases.html", file = "map_covid_cases.png",
cliprect = "viewport")

```

