---
title: "Metropolitan Areas (Deaths & Case)"
output: html_notebook
---


```{r}
# ----------- LOAD PACKAGES ------------- # 

library(tidyverse)
library(tidycensus) # US census bureau data
library(zoo) # rolling mean

# plotting 
library(ggplot2)
library(hrbrthemes) 
library(geofacet) 


# ----------- LOADING DATASETS ----------- # 

# metropolitan state areas delineation from file taken off Census Bureau
data <- read_csv("msa.csv")

#nytimes county-level cases & deaths data from online link 
nyt <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

# census data API, variables can be changed here 
census <- get_acs(geography = "county",
                   variables = c(population = "B01003_001E"), # total population), # black veterans 
                   output = "wide",
                   county = "",
                   year = 2018) 


```


```{r}
# ------------------------------------------------------- #
# -----------  DATA MANIPULATION FOR CBSA --------------- # 
# ------------------------------------------------------- #

# --- *** --- core-based statistical areas  --- *** --- 
# comprised of counties 
# is a U.S. geographic area defined by the Office of Management and Budget (OMB) that consists of one or more counties (or equivalents) anchored by an urban center of at least 10,000 people plus adjacent counties that are socioeconomically tied to the urban center by commuting.
# https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas

# select only cbsa-related information 
data_cbsa <- data %>% 
  mutate(fips = paste(`FIPS State Code`, `FIPS County Code`, sep = "")) %>%
  mutate(fips_state = `FIPS State Code`) %>%
  mutate(state = `State Name`) %>%
  mutate(fips_county = `FIPS County Code`) %>%
  rename(cbsa = `CBSA Code`) %>%
  rename(cbsa_title = `CBSA Title`) %>% 
  select(cbsa, cbsa_title, fips, state, fips_state, fips_county)

# join cbsa data and census data by GEOID/FIPS, get population (and other demographic) info.
census_cbsa_merge <- census %>% 
  rename(fips = GEOID) %>% 
  left_join(data_cbsa, by = "fips") %>% 
  group_by(cbsa) %>%
  mutate(cbsa_population = sum(population))


# -------- FILTER OR NOT? ----------- # 
# only top 12 csa and census data (run this)

# list of top cbsas by population, if we want
# top_cbsa_popn <- census_cbsa_merge %>%
#   select(cbsa, cbsa_title, cbsa_population) %>%
#   arrange(desc(cbsa_population)) %>%
#   distinct() %>%
#   na.omit() %>%
#   data.frame() %>%
#   slice(1:12)

# census_cbsa <- census_cbsa_merge %>%
#   semi_join(top_cbsa_popn, by="cbsa")

# --------------------------------------# 
# without filtering (run this)
census_cbsa <- census_cbsa_merge
# ------------------------------------ #

# only need county to merge both databsets, will keep just metro areas (csa)
cbsa_covid_merge <- census_cbsa %>% 
  left_join(nyt, by = "fips") %>% 
  select(cbsa, cbsa_title, cbsa_population, date, cases, deaths) %>% 
  filter(date >= lubridate::as_date("2020-01-24") & 
           date <= lubridate::as_date("2020-10-18")) # so that the 7 day mean wouldn't get messed up

# get 7-day mean of cases with zoo::rolling mean and dplyr::lag function 
cbsa_covid_cases <- data.frame(cbsa_covid_merge) %>% 
  group_by(cbsa, date) %>% 
  dplyr::summarise(cases_sum = sum(cases, na.rm = TRUE)) %>% 
  mutate(new_cases = cases_sum - dplyr::lag(x = cases_sum, n = 1, order_by = date)) %>%
  mutate(new_cases_mean = rollmean(new_cases, k = 7, fill = NA))

# same as above, but for deaths
cbsa_covid_deaths <- data.frame(cbsa_covid_merge) %>% 
  group_by(cbsa, date) %>% 
  dplyr::summarise(deaths_sum = sum(deaths, na.rm = TRUE)) %>% 
  mutate(new_deaths = deaths_sum - dplyr::lag(x = deaths_sum, n = 1, order_by = date)) %>%
  mutate(new_deaths_mean = rollmean(new_deaths, k = 7, fill = NA))
  
# join deaths and cases numbers together (not sure if I can do it in one?)
# contains
cbsa_covid <- cbsa_covid_merge %>% 
  left_join(cbsa_covid_cases, by = c("cbsa", "date")) %>% 
  left_join(cbsa_covid_deaths, by = c("cbsa", "date")) %>% 
  arrange(desc(cbsa_population))

# final count of cbsa cases, in order to get ranking
cbsa_covid_sum <- cbsa_covid %>% 
  group_by(cbsa, cbsa_title, cbsa_population) %>%
  mutate(cases = sum(cases)) %>% 
  mutate(deaths = sum(deaths)) %>%
  arrange(desc(cases)) %>% 
  select(cbsa, cbsa_title, cbsa_population, cases, deaths) %>% 
  distinct() %>% 
  na.omit()


# ----------------- MOST USEFUL DATASETS ------------------------- # 

# time series data of all new cases per day (7-day rolling average) during time period specified
# names: names(cbsa_covid)
head(cbsa_covid, 10)


# Rank of CBSAs according to total cases
head(cbsa_covid_sum, 10)

# ----------------------------------------------------------------- #
```



```{r}

# ------------------------------------------------------------------- #
# -----------  DATA MANIPULATION TO GET DATA BY STATE --------------- # 
# ------------------------------------------------------------------- #

# similarly, calculate rolling daily 7-day average separately for cases
nyt_state_cases <- nyt %>% 
  group_by(state, date) %>%
  dplyr::summarise(cases_sum = sum(cases, na.rm = TRUE)) %>% 
  mutate(new_cases_state = cases_sum - dplyr::lag(x = cases_sum, n = 1, order_by = date)) %>%
  mutate(new_cases_state_mean = rollmean(new_cases_state, k = 7, fill = NA))

# rolling daily 7-day average for deaths
nyt_state_deaths <- nyt %>% 
  group_by(state, date) %>%
  dplyr::summarise(deaths_sum = sum(deaths, na.rm = TRUE)) %>% 
  mutate(new_deaths_state = deaths_sum - dplyr::lag(x = deaths_sum, n = 1, order_by = date)) %>%
  mutate(new_deaths_state_mean = rollmean(new_deaths_state, k = 7, fill = NA))

# combined total figures
state_covid <- nyt_state_cases %>% 
  left_join(nyt_state_deaths, by = c("state", "date")) %>%
  filter(date >= lubridate::as_date("2020-01-24") & 
         date <= lubridate::as_date("2020-10-18")

# preview
head(state_covid, 10)
```



```{r}

# -------------------- FUNCTION TO MAKE A PLOT FOR ONE STATE  ------------------- # 

stateData <- function(state_name) {
  state_covid %>% 
    filter(state == state_name)
}

metroData <- function(cbsa_id) {
  cbsa_covid %>% 
    filter(cbsa == cbsa_id)
}

covidCasesPlot <- function(state_data, state_name, metro_data) {
  
  ggplot() + 
    geom_line(aes(x = state_data$date, y = state_data$new_cases_state_mean, color = "State"), size = 1.2) + 
    geom_line(aes(x = metro_data$date, y = metro_data$new_cases_mean, color = "Metropolitan Area"), size = 1.2) + 
    labs(x = "\nTime Period", 
       y = "7-day average of Cases and Deaths\n",
       title = paste("COVID-19 Cases in", state_name, "and Metropolitan Area\n")) + 
    scale_color_manual(name = "Colors", 
                       values = c("State" = "coral2", "Metropolitan Area" = "cadetblue")) +
    theme_minimal() 
    
}

covidDeathsPlot <- function(state_data, state_name, metro_data) {
  
  ggplot() + 
    geom_line(aes(x = state_data$date, y = state_data$new_deaths_state_mean, color = "State"), size = 1.2) + 
    geom_line(aes(x = metro_data$date, y = metro_data$new_deaths_mean, color = "Metropolitan Area"), size = 1.2) + 
    labs(x = "\nTime Period", 
       y = "7-day average of Cases and Deaths\n",
       title = paste("COVID-19 Deaths in", state_name, "and Metropolitan Area\n")) + 
    scale_color_manual(name = "Colors", 
                       values = c("State" = "coral4", "Metropolitan Area" = "darkcyan")) +
    theme_minimal() 
    
}

```

`
```{r}

# --------------------- TO MAKE A PLOT FOR ONE STATE -------------------------- # 

# Miami & Florida 
fl_covid <- stateData("Florida")
miami_covid <- metroData(33100) # from cbsa table

a <- covidCasesPlot(fl_covid, "Florida State", miami_covid) # cases
b <- covidDeathsPlot(fl_covid, "Florida State", miami_covid) # deaths


# NYC & New York cases
ny_covid <- stateData("New York")
nyc_covid <- metroData(35620)

c <- covidCasesPlot(ny_covid, "New York State", nyc_covid) # cases
d <- covidDeathsPlot(ny_covid, "New York State", nyc_covid) # deaths

# Dallas-Fort Worth-Arlington (19100) & Texas
tx_covid <- stateData("Texas")
dal_covid <- metroData(19100)

e <- covidCasesPlot(tx_covid, "Texas State", dal_covid) # cases
f <- covidDeathsPlot(tx_covid, "Texas State", dal_covid) # deaths



```

