---
title: "Visualizations: Metropolitan Areas per Capita, Wave I, II, III (Deaths)"
output: html_notebook 
---

# CONTENTS OF THIS SCRIPT   
  
### Loading Packages 
### Datasets 
### Merging County data to Top 50 populated MSA & Region Dataset (for spatial attributes)
### Adding Spatial Attributes 
### Filtering by waves
### Visualization in Maps


```{r message = FALSE}
# ----------- LOAD PACKAGES ------------- # 

library(tidyverse)
library(tidycensus)

# plotting 
library(ggplot2)
library(ggthemes)
library(showtext)

showtext_auto()

font_add(family = "raleway", regular = "C:/Users/louis/Dropbox/Stuff/Fonts/Raleway-Regular.ttf")


```


```{r cache = TRUE}  

# ----------- LOADING DATASETS ----------- # 

# MSA Things
# from Sydney
msa_index <- read_csv("data/msa/msa_mix_index.csv") # csa and msa with population 
covid <- read_csv("data/msa/us_daily_msa_split_2020-11-16.csv") # split 

# metropolitan state areas delineation from file taken off Census Bureau
msa <- read_csv("data/msa.csv") # using this bc FIPS code needs to be 5 digits


# -------------- MSA_INDEX dataset check
# top 50 most populated csa and msas
# msa_index %>% 
#   select("mix_index") %>% 
#   distinct() %>% 
#   count()

# -------------- MSA_SPLIT dataset check
# Regional minus State count 
# CSA/MSA count 

# View(msa)
```

# Adding County Data (to match with spatial lines)

```{r}

# need to merge county back in to get the lines 

# # rename to get 5-digit fips, select only needed variables, remove NAs
msa_w_fips <- msa %>%
  mutate(fips = paste(`FIPS State Code`, `FIPS County Code`, sep = "")) %>% #
  select(fips, `CSA Title`, `County/County Equivalent`, `State Name`) 

# # left join index of 50 with fips codes
# msa_index_fips <- msa_index %>% 
#   left_join(msa_w_fips, by = c("CSA Title", "County/County Equivalent", "State Name")) %>% 
#   rename(county = `County/County Equivalent`) %>% 
#   rename(csa = `CSA Title`) %>%
#   rename(state = `State Name`) %>%
#   rename(agg_index = mix_index)

msa_index_2 <- msa_index %>% 
  rename(county = `County/County Equivalent`) %>% 
  rename(csa = `CSA Title`) %>%
  rename(state = `State Name`) %>%
  rename(agg_index = mix_index) %>% 
  rename(fips = FIPS_combined) %>% 
  names()
  
# anti join to get the counties not in msa_index 
region_fips <- msa_w_fips %>% 
  anti_join(msa_index, by = "CSA Title") %>% 
  rename(county = `County/County Equivalent`) %>%
  mutate(agg_index = `State Name`) %>%
  rename(state = `State Name`) %>%
  rename(csa = `CSA Title`) 

# joining fips info with covid dataset (has states + selected msas)
state_msa_fips_join <- covid %>% 
  full_join(msa_index_fips, by = "agg_index")# %>% 

# keeping only msas and counties, since they have fips
msa_covid_only <- state_msa_fips_join %>%
  drop_na(fips)

# keeping only states, don't have counties
state_covid_only <- state_msa_fips_join %>% 
  anti_join(msa_covid_only) %>% 
  select(-fips, -mix_index_population, -FIPS_population, -FIPS_combined, -`Central/Outlying County`, -state, -county, -csa, -`Metropolitan Division Title`)



# problematic with states without fips 
# region_fips_join <- msa_region %>% 
#   full_join(region_fips, by = "agg_index") %>%
#   drop_na(fips)


# final_daily <- msa_fips_join %>% # or final total 
#   bind_rows(region_fips_join) %>% 
#   select(index, Date, state, agg_index, fips, csa, county, population, 
#          Confirmed, Deaths, new_confirmed, new_deaths, 
#          new_confirmed_7, new_deaths_7, new_confirmed_14, new_deaths_14,
#          per_100k_new_confirmed_7, per_100k_new_deaths_7)
#          
# names(final_daily)
# write.csv(final_daily, "data/final-50-county-daily.csv")

```
  

# Getting Wave Count 

```{r}

wave_2 <- as.Date("2020-06-15") # start of wave 2
wave_3 <- as.Date("2020-10-15") # start of wave 3

state_covid_only <- state_covid_only %>% 
  rename("NAME" = "agg_index") %>%
  filter(! NAME %in% c("Alaska", "Hawaii", "Rhode Island", "District of Columbia"))


state_total <- state_covid_only %>% 
  filter(Date == max(as.Date(state_covid_only$Date), na.rm = TRUE)) %>% # need to remove NA
  mutate(Date_Total = Date)

state_w2_start <- state_covid_only %>% 
  filter(Date == max(wave_2)) %>%
  mutate(Date_W2 = Date)

state_w3_start <- state_covid_only %>% 
  filter(Date == max(wave_3)) %>% 
  mutate(Date_W3 = Date)

state_all <- state_total %>% 
  # joining wave 2 and beyond numbers
  left_join(state_w2_start, by = "NAME") %>% 
  rename(Confirmed_total = Confirmed.x) %>%
  rename(Deaths_total = Deaths.x) %>%
  # wave 1 only %>% 
  mutate(Confirmed_W1 = Confirmed.y) %>% 
  mutate(Deaths_W1 = Deaths.y) %>%
  # wave 2 and beyond column 
  mutate(Confirmed_W2_plus = Confirmed_total - Confirmed.y) %>% 
  mutate(Deaths_W2_plus = Deaths_total - Deaths.y) %>% 
  # joining wave 3 numbers 
  left_join(state_w3_start, by = "NAME") %>%
  # only wave 2 
  mutate(Deaths_W2_only = Deaths - Deaths_W2_plus) %>% 
  mutate(Confirmed_W2_only = Confirmed - Confirmed_W2_plus) %>% 
  # wave 3 and beyond
  mutate(Deaths_W3 = Deaths_total - Deaths) %>% 
  mutate(Confirmed_W3 = Confirmed_total - Confirmed) %>%
  # tidy up, selecting only relevant variables
  select(index, NAME, population, 
         Date_Total, Confirmed_total, Deaths_total, 
         Confirmed_W1, Deaths_W1,
         Date_W2, Confirmed_W2_plus, Confirmed_W2_only, Deaths_W2_plus, Deaths_W2_only, 
         Date_W3, Confirmed_W3, Deaths_W3)
  
 
View(state_all)
```

    
# Adding spatial attributes  
  
```{r cache = TRUE}

# Adding spatial attributes

library(sf)
library(jsonlite) # from FIPS -> Geo (lat, long)
library(gridExtra) # for grid plot

county_lines <- st_read("data/county_shape/cb_2018_us_county_500k.shp")
state_lines <- st_read("data/state_shape/cb_2018_us_state_500k.shp")

# merge county 
# add FIPS as a variable from State Fips and County Fips
county_lines <- county_lines %>% 
  mutate(fips = paste(STATEFP, COUNTYFP, sep = ""))

# add lat long attributes to county dataset          
county_geo <- merge(county_lines, msa_covid_only, by = "fips")
county_map <- county_geo %>% st_transform('+proj=longlat +datum=WGS84') 


# merge state 
# add lat long attributes to state dataset 

state_geo <- merge(state_lines, state_all, by = "NAME")
state_map <- state_geo %>% st_transform('+proj=longlat +datum=WGS84')



```


# Visualizations (finally)  
  
```{r}

options(scipen = 999)

library(usmap) # to get US Map Data
library(cowplot) # for grid plot

names(map_w2)
fips("New York")
#state_name, 

g_total <- ggplot(data = state_map) +
  geom_sf(aes(fill = Deaths_total/population), size = 0.3) +  # color = NA 
  scale_fill_viridis_c(name = "Deaths per Capita", option = "viridis", direction = -1) + 
  labs(title = "Total Deaths\n") + 
  theme_void() + 
  theme(text = element_text(family = "raleway", size = 50))

g_w1 <- ggplot(data = state_map) +
  geom_sf(aes(fill = Deaths_W1/population), size = 0.3) + 
  scale_fill_viridis_c(name = "Deaths per Capita", option = "viridis", direction = -1) + 
  labs(title = "Wave 1 Deaths Only\n") + 
  theme_void() + 
  theme(text = element_text(family = "raleway", size = 50))

g_w2 <- ggplot(data = state_map) +
  geom_sf(aes(fill = Deaths_W2_only/population), size = 0.3) + 
  scale_fill_viridis_c(name = "Deaths per Capita", option = "viridis", direction = -1) + 
  labs(title = "Wave 2 Deaths Only\n") + 
  theme_void() + 
  theme(text = element_text(family = "raleway", size = 50))


g_w3 <- ggplot(data = state_map) +
  geom_sf(aes(fill = Deaths_W3/population), size = 0.3) + 
  scale_fill_viridis_c(name = "Deaths per Capita", option = "viridis", direction = -1) + 
  labs(title = "Wave 3 Deaths Onwards\n") + 
  theme_void() + 
  theme(text = element_text(family = "raleway", size = 50))


p <- plot_grid(g_total, g_w2, g_w3, ncol = 3)

title <- ggdraw() + 
  draw_label("Total Deaths per Capita in U.S. by State per Wave", fontface='bold') + 
  theme(text = element_text(family = "raleway"))

plot_grid(title, p, ncol=1, rel_heights=c(0.1, 1))

# ggsave("viz/state-waves.png", width = 8, height = 3, dpi = 300)
ggsave("viz/state-waves-total.png", g_total, width = 8, height = 5, dpi = 300)
ggsave("viz/state-waves-W1.png", g_w1, width = 8, height = 5, dpi = 300)
ggsave("viz/state-waves-W2.png", g_w2, width = 8, height = 5, dpi = 300)
ggsave("viz/state-waves-W3.png", g_w3, width = 8, height = 5, dpi = 300)

```

