---
title: "Metropolitan Areas (Deaths & Case)"
output: html_notebook
---

# Data Manipulation  
  
```{r}
# ----------- LOAD PACKAGES ------------- # 

library(tidyverse)
library(tidycensus) # US census bureau data
library(zoo) # rolling mean

# plotting 
library(ggplot2)
library(ggthemes)
library(showtext)

showtext_auto()

font_add(family = "raleway", regular = "C:/Users/louis/Dropbox/Stuff/Fonts/Raleway-Regular.ttf")


```

```{r cache = TRUE}


# ----------- LOADING DATASETS ----------- # 

# set working directory to source file location

# metropolitan state areas delineation from file taken off Census Bureau
msa <- read_csv("data/msa.csv")

#nytimes county-level cases & deaths data from online link 
covid <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

# census data API, variables can be changed and added here 
census <- get_acs(geography = "county",
                   variables = c(population = "B01003_001E"), # total population
                   output = "wide",
                   county = "",
                   year = 2018) # ACS 2018 Survey

# US City & FIPS code boundaries 
# https://simplemaps.com/data/us-cities license 
city <- read_csv("data/uscities.csv")

```


```{r}

# ---------------------------------------------------------- #
# -----------  DATA MANIPULATION FOR COUNTY  --------------- # 
# ---------------------------------------------------------- #


county_sum_total <- covid %>%
  filter(date == max(covid$date)) # latest 

# wave 2 
county_sum_wave_2_start <- covid %>%
  filter(date == "2020-06-15") # %>% # latest 

county_sum_w2 <- county_sum_total %>% 
  inner_join(county_sum_wave_2_start, by = c("fips", "county")) %>% 
  mutate(cases = cases.x - cases.y) %>%
  mutate(deaths = deaths.x - deaths.y) %>% 
  rename(start_date = date.y) %>% 
  rename(end_date = date.x) %>%
  select(fips, county, all_of(population), start_date, end_date, cases, deaths)




# DATA WITH POPULATION
county_census <-census %>% 
  rename(fips = GEOID) %>% 
  left_join(covid, by = "fips")


county_census_total <- county_census %>% 
  filter(date == "2020-11-14")
# idk why max isn't working

# WAVE 2 
county_census_sum_w2_start <- county_census %>%
  filter(date == "2020-06-15") 

county_census_sum_w2 <- county_census_total %>% 
  inner_join(county_census_sum_w2_start, by = c("fips", "county", "population", "state")) %>% 
  mutate(cases = cases.x - cases.y) %>%
  mutate(deaths = deaths.x - deaths.y) %>% 
  rename(start_date = date.y) %>% 
  rename(end_date = date.x) %>%
  select(fips, county, population, start_date, end_date, cases, deaths)

county_census_sum_w2

View(county_census_sum_w2)
dim(county_census_sum_w2)
```

```{r}

# ------------------------------------------------------- #
# -----------  DATA MANIPULATION FOR MSA --------------- # 
# ------------------------------------------------------- #

# --- *** --- metropolitan statistical areas  --- *** --- 
# only 31 MSA in this list
# comprised of counties 
# is a U.S. geographic area defined by the Office of Management and Budget (OMB) that consists of one or more counties (or equivalents) anchored by an urban center of at least 10,000 people plus adjacent counties that are socioeconomically tied to the urban center by commuting.
# https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas


# select only msa-related information 
data_msa <- msa %>% 
  mutate(fips = paste(`FIPS State Code`, `FIPS County Code`, sep = "")) %>%
  mutate(fips_state = `FIPS State Code`) %>%
  mutate(state = `State Name`) %>%
  mutate(fips_county = `FIPS County Code`) %>%
  rename(msa = `Metropolitan Division Code`) %>%
  rename(msa_title = `Metropolitan Division Title`) %>% 
  select(msa, msa_title, fips, state, fips_state, fips_county)

data_msa$fips

# join msa data and census data by GEOID/FIPS, get population (and other demographic) info.
census_msa_merge <- census %>% 
  rename(fips = GEOID) %>% 
  left_join(data_msa, by = "fips") %>% 
  group_by(msa) %>%
  mutate(msa_population = sum(population))

census_msa_merge$fips

# -------- FILTER OR NOT? ----------- # 
# only top 12 msa and census data (run this)

# list of top msas by population, if we want
top_msa_popn <- census_msa_merge %>%
  select(msa, msa_title, msa_population) %>%
  arrange(desc(msa_population)) %>%
  distinct() %>%
  na.omit() %>%
  data.frame() %>%
  slice(1:12)

top_census_msa <- census_msa_merge %>%
  semi_join(top_msa_popn, by="msa")

# --------------------------------------# 
# without filtering (run this)
census_msa <- census_msa_merge

# ------------------------------------ #

# only need county to merge both datasets, will keep just metro areas (csa)
msa_county_covid_merge <- census_msa %>% 
  left_join(covid, by = c("fips", "state")) %>%
  select(!B01003_001M) %>%
  drop_na(msa)

# ###########
# sum of county, showing msa as well 
msa_county_sum <- msa_county_covid_merge %>%
  filter(date == max(date))
# ###########

# join nytimes county-covid df with population and msa areas (remove county)
msa_covid_merge <- msa_county_covid_merge %>% 
  select(msa, msa_title, msa_population, date, cases, deaths) %>% 
  # set date range
  filter(date >= lubridate::as_date("2020-01-24") &
           date <= lubridate::as_date(Sys.Date() - 8)) # 8 days prior, so that the 7 day mean wouldn't get messed up

# get 7-day mean of cases with zoo::rolling mean and dplyr::lag function 
msa_covid_cases <- data.frame(msa_covid_merge) %>% 
  group_by(msa, date) %>% 
  dplyr::summarise(cases_sum = sum(cases, na.rm = TRUE)) %>% 
  mutate(new_cases = cases_sum - dplyr::lag(x = cases_sum, n = 1, order_by = date)) %>% 
  # rollmean function from zoo package to help calculate rolling mean, k = no. of days
  mutate(new_cases_mean = zoo::rollmean(new_cases, k = 7, fill = NA)) 

# same as above, but for deaths
msa_covid_deaths <- data.frame(msa_covid_merge) %>% 
  group_by(msa, date) %>% 
  dplyr::summarise(deaths_sum = sum(deaths, na.rm = TRUE)) %>% 
  mutate(new_deaths = deaths_sum - dplyr::lag(x = deaths_sum, n = 1, order_by = date)) %>%
  # rollmean function from zoo package to help calculate rolling mean, k = no. of days
  mutate(new_deaths_mean = zoo::rollmean(new_deaths, k = 7, fill = NA))
  
# join deaths and cases numbers together (not sure if I can do it in one?)
# contains
msa_covid <- msa_covid_merge %>% 
  left_join(msa_covid_cases, by = c("msa", "date")) %>% 
  left_join(msa_covid_deaths, by = c("msa", "date")) %>% 
  arrange(desc(msa_population)) # arrange by msa with highest population 

# final count of msa cases, in order to get ranking
msa_covid_sum <- msa_covid %>% 
  filter(date == max(msa_covid$date)) %>% 
  select(msa, msa_title, msa_population, date, cases_sum, deaths_sum) %>% 
  distinct() %>%
  drop_na(msa)

# ----------------- MOST USEFUL DATASETS ------------------------- # 

# time series data of all new cases per day (7-day rolling average) during time period specified
# names: names(msa_covid)
head(msa_covid, 50)

# Rank of MSAs according to total cases
head(msa_covid_sum, 50)

head(msa_county_sum)

# ----------------------------------------------------------------- #
```



```{r}

# ------------------------------------------------------------------- #
# -----------  DATA MANIPULATION TO GET DATA BY STATE --------------- # 
# ------------------------------------------------------------------- #

# similarly, calculate rolling daily 7-day average separately for cases
covid_state_cases <- covid %>% # nyt dataset 
  group_by(state, date) %>%
  dplyr::summarise(cases_sum = sum(cases, na.rm = TRUE)) %>% 
  mutate(new_cases_state = cases_sum - dplyr::lag(x = cases_sum, n = 1, order_by = date)) %>%
  mutate(new_cases_state_mean = rollmean(new_cases_state, k = 7, fill = NA))

# rolling daily 7-day average for deaths
covid_state_deaths <- covid %>% 
  group_by(state, date) %>%
  dplyr::summarise(deaths_sum = sum(deaths, na.rm = TRUE)) %>% 
  mutate(new_deaths_state = deaths_sum - dplyr::lag(x = deaths_sum, n = 1, order_by = date)) %>%
  mutate(new_deaths_state_mean = rollmean(new_deaths_state, k = 7, fill = NA))

# combined total figures
state_covid <- covid_state_cases %>% 
  left_join(covid_state_deaths, by = c("state", "date")) %>%
  filter(date >= lubridate::as_date("2020-01-24") & 
         date <= lubridate::as_date(Sys.Date() - 8))

# preview
head(state_covid, 10)


# final count of msa cases, in order to get ranking
state_sum <- state_covid %>% 
  filter(date == max(state_covid$date)) %>% 
  select(state, date, cases_sum, deaths_sum) %>% 
  distinct() 


```

```{r}

# --------------------------------------------------------- #
# ----------- GETTING STATE & MSA TOGETHER ---------------- # 
# --------------------------------------------------------- #

# making both datasets bindable 
msa_covid_sum_merge <- msa_covid_sum %>% 
  rename(msa_state = "msa_title") %>% 
  ungroup() %>%
  select(msa_state, date, cases_sum, deaths_sum)

state_covid_sum_merge <- state_sum %>% 
  rename(msa_state = "state") %>% 
  select(msa_state, date, cases_sum, deaths_sum)

# binding row  
msa_state_covid_sum <- msa_covid_sum_merge %>%
  bind_rows(state_covid_sum_merge)
  

```



```{r}

# ------------------------------------------- #
# ----------- GETTING CITIES ---------------- # 
# ------------------------------------------- #

# cities are actually smaller than counties, e.g. New York City is part of New York County
# some are incorporated, and some would have mayors 
# this is useful data also to get labels and plot points

head(city)
```
  
    
# Visualizations 

## Covid Line Graph (7-day average) per State

```{r}

# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\\/\/\/ #
# *************** FUNCTION: PLOT DAILY COVID ONE STATE GRAPH ********************** # 
# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\\/\/\/ #

# plot line graph of daily cases for state and metropolitan area 

# choose state name
stateData <- function(state_name) {
  state_covid %>% 
    filter(state == state_name)
}

# choose metropolitan state area ID 
# find them here: head(msa_covid_sum, 10)
metroData <- function(msa_id) {
  msa_covid %>% 
    filter(msa == msa_id)
}

# line graph
covidCasesPlot <- function(state_data, state_name, metro_data) {
  
  ggplot() + 
    geom_line(aes(x = state_data$date, y = state_data$new_cases_state_mean, color = "State"), size = 1.2) + 
    geom_line(aes(x = metro_data$date, y = metro_data$new_cases_mean, color = "Metropolitan Area"), size = 1.2) + 
    labs(x = "\nTime Period", 
       y = "7-day average of Cases and Deaths\n",
       title = paste("COVID-19 Cases in", state_name, "and Metropolitan Area\n")) + 
    scale_color_manual(name = "Colors", 
                       values = c("State" = "coral2", "Metropolitan Area" = "cadetblue")) +
    theme_minimal() 
    
}

covidDeathsPlot <- function(state_data, state_name, metro_data) {
  
  ggplot() + 
    geom_line(aes(x = state_data$date, y = state_data$new_deaths_state_mean, color = "State"), size = 1.2) + 
    geom_line(aes(x = metro_data$date, y = metro_data$new_deaths_mean, color = "Metropolitan Area"), size = 1.2) + 
    labs(x = "\nTime Period", 
       y = "7-day average of Cases and Deaths\n",
       title = paste("COVID-19 Deaths in", state_name, "and Metropolitan Area\n")) + 
    scale_color_manual(name = "Colors", 
                       values = c("State" = "coral4", "Metropolitan Area" = "darkcyan")) +
    theme_minimal() 
    
}

```

  
### Examples   
  
```{r}

# ---- To Find MSA codes ---- #

# head(msa_covid_sum, 10)



# ----------------- EG TO MAKE A DAILY CASES/ DEATHS PLOT FOR ONE STATE ------------------- # 

# Miami & Florida 
fl_covid <- stateData("Florida")
miami_covid <- metroData(33124) # from msa table

a <- covidCasesPlot(fl_covid, "Florida State", miami_covid) # cases
b <- covidDeathsPlot(fl_covid, "Florida State", miami_covid) # deaths


# NYC & New York cases
ny_covid <- stateData("New York")
nyc_covid <- metroData(35614)

c <- covidCasesPlot(ny_covid, "New York State", nyc_covid) # cases
d <- covidDeathsPlot(ny_covid, "New York State", nyc_covid) # deaths

# Dallas-Fort Worth-Arlington (19100) & Texas
tx_covid <- stateData("Texas")
dal_covid <- metroData(19124)

e <- covidCasesPlot(tx_covid, "Texas State", dal_covid) # cases
f <- covidDeathsPlot(tx_covid, "Texas State", dal_covid) # deaths


```



## Geo Mapping Visualizations  
  
### County Cases   
  
```{r}
# Plot State Map with Metro Areas 

library(sf)

library(usmap) # to get US Map Data

library(jsonlite) # from FIPS -> Geo (lat, long)

# library(cowplot)
library(gridExtra) # for grid plot


# get lat long data from US Census 
# https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html
county_lines <- st_read("data/county_shape/cb_2018_us_county_500k.shp")
state_lines <- st_read("data/state_shape/cb_2018_us_state_500k.shp")

names(state_sum)
head(state_lines)


# merge county 
# add FIPS as a variable from State Fips and County Fips
county_lines <- county_lines %>% 
  mutate(fips = paste(STATEFP, COUNTYFP, sep = ""))
# add lat long attributes to county dataset          
county_geo <- merge(county_lines, county_sum, by = "fips")
county_map <- county_geo %>% st_transform('+proj=longlat +datum=WGS84') 

county_geo_w2 <- merge(county_lines, county_sum_w2, by = "fips")
county_map_w2 <- county_geo_w2 %>% st_transform('+proj=longlat +datum=WGS84') 

# census county, wave 2
county_census_geo_w2 <- merge(county_lines, county_census_sum_w2, by = "fips") 
county_census_map_w2 <- county_census_geo_w2 %>% st_transform('+proj=longlat +datum=WGS84') 


# merge MSA
msa_geo <- merge(county_lines, msa_county_sum, by = "fips")
msa_map <- msa_geo %>% st_transform('+proj=longlat +datum=WGS84') 

# merge states and state lines
state_lines <- state_lines %>% 
  rename(state = NAME)
state_geo <- merge(state_lines, state_sum, by = "state")
state_map <- state_geo %>% st_transform('+proj=longlat +datum=WGS84') 


# remove non-mainland US parts 
# outside_mainland <- c("02", "15", "72", "2", "3")
outside_mainland <- c("Alaska", 
                      "Hawaii", 
                      "Puerto Rico", 
                      "Virgin Islands", 
                      "Northern Mariana Islands",
                      "Guam")


county_map_US <- county_map %>% 
  filter(!state %in% outside_mainland)

county_map_US_w2 <- county_map_w2 %>% 
  filter(!state %in% outside_mainland)

county_census_map_US_w2 <- county_census_map_w2 %>% 
  filter(!state %in% outside_mainland)

# --- 

msa_map_US <- msa_map %>% 
  filter(!state %in% outside_mainland)

state_map_US <- state_map %>% 
  filter(!state %in% outside_mainland) %>% 
  rename(cases = cases_sum) %>% 
  rename(deaths = deaths_sum)

names(state_map_US)

# --- 
# PLOTS 

ggplot(data = county_map_US) +
  geom_sf(aes(fill = cases)) + 
  scale_fill_viridis_c(option = "magma", direction = 1)

ggplot(data = msa_map_US) +
  geom_sf(aes(fill = cases)) + 
  scale_fill_viridis_c(option = "magma", direction = 1)

ggplot() +
  geom_sf(data = state_map_US, aes(fill = cases)) + 
  geom_sf(data = msa_map_US, aes(fill = cases)) + 
  scale_fill_viridis_c(option = "magma", direction = -1) + 
  theme_void()

ggplot(data = state_map_US) +
  geom_sf(aes(fill = cases)) + 
  scale_fill_viridis_c(option = "magma", direction = -1) + 
  theme_void()

# save to image function - last plot 
# ggsave("state-msa-us.png", width = 8, height = 5, dpi = 300)
```


```{r}
# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\\/\/\/ #
# *************** FUNCTION: PLOT DAILY COVID ONE STATE GRAPH ********************** # 
# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\\/\/\/ #

# county state map 
county_state_map <- function(state_name) {
  
  fips_code <- fips(state = state_name) 

  county_map_state <- county_map %>% 
  filter(STATEFP == fips_code) 
  
  ggplot(data = county_map_state) +
    geom_sf(aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = paste(state_name),
         subtitle = "Total Cases") +
    theme_void() 
    
}


# census 

county_pax_cases_w2 <- function(state_name) {
  
  fips_code <- fips(state = state_name) 

  county_census_map_state <- county_census_map_US_w2 %>% 
    filter(STATEFP == fips_code) %>%
    filter(cases >= 0)
  
  ggplot(data = county_census_map_state) +
    geom_sf(aes(fill = cases/population)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = paste(state_name),
         subtitle = "Cases per Capita after Second Wave") +
    theme_void() + 
    theme(text = element_text(family = "raleway", size = 25))
  
}

county_pax_deaths_w2 <- function(state_name) {
  
  fips_code <- fips(state = state_name) 

  county_census_map_state <- county_census_map_US_w2 %>% 
    filter(STATEFP == fips_code) %>% 
    filter(deaths >= 0)
  
  ggplot(data = county_census_map_state) +
      geom_sf(aes(fill = deaths/population)) + 
      scale_fill_viridis_c(option = "viridis", direction = -1) + 
      labs(title = paste(state_name),
           subtitle = "Deaths per Capita after Second Wave") +
      theme_void() + 
      theme(text = element_text(family = "raleway", size = 25))
  
}


county_state_map_w2 <- function(state_name) {
  
  fips_code <- fips(state = state_name) 

  county_map_state <- county_map_w2 %>% 
  filter(STATEFP == fips_code) 
  
  ggplot(data = county_map_state) +
    geom_sf(aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = paste(state_name),
         subtitle = "After Second Wave") +
    theme_void()
    
}


# e.g. 
TX <- county_state_map("Texas")
CA <- county_state_map("California")
FL <- county_state_map("Florida")
MA <- county_state_map("Massachusetts")
NY <- county_state_map("New York")
NJ <- county_state_map("New Jersey")
IL <- county_state_map("Illinois")
GA <- county_state_map("Georgia")

# cases after second wave 
# e.g. 
TX_w2 <- county_state_map_w2("Texas")
CA_w2 <- county_state_map_w2("California")
FL_w2 <- county_state_map_w2("Florida")
MA_w2 <- county_state_map_w2("Massachusetts")
NY_w2 <- county_state_map_w2("New York")

NJ_w2 <- county_state_map_w2("New Jersey")
IL_w2 <- county_state_map_w2("Illinois")
GA_w2 <- county_state_map_w2("Georgia")


county_pax_w2

CA_pax_w2_cases <- county_pax_cases_w2("California")
CA_pax_w2_deaths <- county_pax_deaths_w2("California")

CA_3 <- county_pax_cases_w2("California")
CA_4 <- county_pax_deaths_w2("California")

NY_3 <- county_pax_cases_w2("New York")
NY_4 <- county_pax_deaths_w2("New York")

IL_3 <- county_pax_cases_w2("Illinois")
IL_4 <- county_pax_deaths_w2("Illinois")

FL_3 <- county_pax_cases_w2("Florida")
FL_4 <- county_pax_deaths_w2("Florida")

WI_3 <- county_pax_cases_w2("Wisconsin")
WI_4 <- county_pax_deaths_w2("Wisconsin")

ND_3 <- county_pax_cases_w2("North Dakota")
ND_4 <- county_pax_deaths_w2("North Dakota")

SD_3 <- county_pax_cases_w2("South Dakota")
SD_4 <- county_pax_deaths_w2("South Dakota")


GA_3 <- county_pax_cases_w2("Georgia")
GA_4 <- county_pax_deaths_w2("Georgia")



# TO DO: 

 fips_code <- fips(state = "New York") 
# Facet it 

plot_grid(TX, TX_w2, 
          CA, CA_w2, 
          FL, FL_w2, 
          IL, IL_w2, 
          MA, MA_w2, 
          NJ, NJ_w2, 
          NY, NY_w2, 
          ncol = 2)

plot_grid(FL_3, FL_4, 
          IL_3, IL_4, 
          ncol = 2)

plot_grid(NY_3, NY_4, 
          CA_3, CA_4,
          WI_3, WI_4,
          GA_3, GA_4,
          ncol = 2)



# ggsave("CA-comparison.png", plot_grid(CA, CA_msa), width = 8, height = 5, dpi = 300)
# ggsave("IL-comparison.png", plot_grid(IL, IL_msa), width = 8, height = 5, dpi = 300)
# ggsave("MA-comparison.png", plot_grid(MA, MA_msa), width = 8, height = 5, dpi = 300)
# 
# ggsave("CA-county-state.png", CA, width = 5, height = 6, dpi = 300)
# ggsave("IL-county-state.png", IL, width = 5, height = 6, dpi = 300)
# ggsave("MA-county-state.png", MA, width = 5, height = 6, dpi = 300)

# ggsave("county-state-waves.png", width = 8, height = 25, dpi = 300)

# ggsave("county-pax-w2_NY_CA_WI_GA.png", width = 14, height = 25, dpi = 300)
# 
# ggsave("county-pax-w2_FL_IL.png", width = 10, height = 8, dpi = 300)


```


```{r}
# msa state map 
msa_state_map <- function(msa) {
  
  msa_map_state <- msa_map %>% 
  filter(msa == msa) 
  
  ggplot(data = msa_map_state) +
    geom_sf(aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = msa_map_state$NAME)
    
}


msa_state_map(40484)

head(msa_county_sum)


msa_map_NWNJ <- msa_map %>% 
  filter(msa == 35084)

31084

msa_map_LA <- msa_map %>% 
  filter(msa == 41884)

msa_map_SF <- msa_map %>% 
  filter(msa == 31084)

msa_map_OC <- msa_map %>% 
  filter(msa == 11244)

msa_map_OAK <- msa_map %>% 
  filter(msa == 36084)

msa_map_RA <- msa_map %>% 
  filter(msa == 42034)

state_map_CA <- state_map_US %>% 
  filter(state == "California") 

state_map_CA_region <- state_map_CA

# state_map_CA <- state_map_CA %>% 
#   mutate(region_cases = cases - msa_map_LA$cases
#          
state_map_CA_region$cases <- state_map_CA$cases -
  sum(msa_map_LA$cases) - 
  msa_map_SF$cases - 
  msa_map_OC$cases - 
  sum(msa_map_OAK$cases) - 
  msa_map_RA$cases

ggplot() +
    geom_sf(data = state_map_CA_region, aes(fill = cases)) + 
    geom_sf(data = msa_map_LA, aes(fill = cases)) + 
    geom_sf(data = msa_map_SF, aes(fill = cases)) + 
    geom_sf(data = msa_map_OC, aes(fill = cases)) + 
    geom_sf(data = msa_map_OAK, aes(fill = cases)) + 
    geom_sf(data = msa_map_RA, aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = state_map_CA$state,
         subtitle = "Metropolitan Statistical Areas") + 
    theme_void()

ggplot() +
    geom_sf(data = state_map_CA, aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(subtitle = state_map_CA$state) + 
    theme_void()

names(msa_map_NWNJ)

### TEXAS ### 

state_map_TX <- state_map_US %>% 
  filter(state == "Texas") 

texas_msa <- msa_county_sum %>% 
  select("state", "msa_title", "msa") %>%
  filter(state == "Texas") %>%
  distinct() 

texas_msa_code <- pull(texas_msa, msa) # get msa codes into a vector

msa_map_TX <- msa_map %>% 
  filter(msa %in% texas_msa_code)

state_map_TX$region_cases <- state_map_TX$cases - sum(msa_map_TX$cases)

ggplot() +
    geom_sf(data = state_map_TX, aes(fill = region_cases)) +
    geom_sf(data = msa_map_TX, aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = state_map_TX$state,
         subtitle = "Metropolitan Statistical Areas") + 
    theme_void()

head(msa_map_TX)


### FUNCTION ### 

msa_state_map_US <- function(state_name) {
  
  # e.g. filter to get state's map
  state_map <- state_map_US %>% 
    filter(state == state_name) 
  
  state_msa <- msa_county_sum %>% 
    select("state", "msa_title", "msa") %>%
    filter(state == state_name) %>%
    distinct() 
  
  # get msas from the state 
  state_msa_code <- pull(state_msa, msa) # get msa codes into a vector
  
  msa_map_state <- msa_map %>% 
    filter(msa %in% state_msa_code)
  
  # get regional numbers
  state_map$region_cases <- state_map$cases - sum(msa_map_state$cases)
  
  #   # get two-letter e.g. NY
  state_code <- state_map$STUSPS
  
  # df <- list()
  # 
  # df$state_map <- state_map 
  # df$msa_map_state <- msa_map_state

#   return(df)
# }  
  # plot
  ggplot() +
    geom_sf(data = state_map, aes(fill = region_cases)) +
    geom_sf(data = msa_map_state, aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) + 
    labs(title = state_map$state) +
         # subtitle = "Metropolitan Statistical Areas") + 
    theme_void()
  
  
} 

# 35614 # nyc is missing

# df_ny <- msa_state_map_US("New York")
# 
# View(df_ny$msa_map_state)
# 
# msa_map %>% 
#   filter(state == "New York")

IL_msa <- msa_state_map_US("Illinois")
CA_msa <- msa_state_map_US("California")
TX_msa <- msa_state_map_US("Texas")
NJ_msa <- msa_state_map_US("New Jersey")
MA_msa <- msa_state_map_US("Massachusetts")
FL_msa <- msa_state_map_US("Florida")

plot_grid(TX_msa, CA_msa, FL_msa, IL_msa, MA_msa, NJ_msa, ncol = 3)

# ggsave("CA-metro-state.png", CA_msa, width = 5, height = 6, dpi = 300)
# ggsave("IL-metro-state.png", IL_msa, width = 5, height = 6, dpi = 300)
# ggsave("MA-metro-state.png", MA_msa, width = 5, height = 6, dpi = 300)
# ggsave("metro-state.png", width = 8, height = 5, dpi = 300)
```
### Metropolitan Cases  
  
```{r}

# in progress 

# limit to state 
# view by state, won't be able to plot all 
# check out why there aren't all 31 MSAs

msa_map <- county_map_US %>% 
  inner_join(top_census_msa, by = "fips")


View(msa_map)

names(top_census_msa)

dim(top_census_msa)


  ggplot(data = msa_map) +
    geom_sf(aes(fill = cases)) + 
    scale_fill_viridis_c(option = "magma", direction = -1) 

```

